name: Run eslint&prettier
on: 
  push:
    branches: [master]
jobs:
  lint:
    name: push
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm
      - name: install modules
        run: yarn install
      - name: prettier test
        run: yarn run prettier
      - name: eslint code
        run: yarn run lint:fix